### PR TITLE
Add loongarch support for lsp-plugins

### PR DESCRIPTION
**Pull request by zhangwenlong8911**

### CODE REVIEW

**Comment by zhangwenlong8911** [comment]
hello i have run command "make -j4 all" and "make -j4 test",the log files as follow:

[lsp-plugins_build_log.txt](https://github.com/sadko4u/lsp-plugins/files/8085115/lsp-plugins_build_log.txt)
[lsp-plugins_test_log.txt](https://github.com/sadko4u/lsp-plugins/files/8085113/lsp-plugins_test_log.txt)

**Comment by sadko4u** [comment]
Ported changes to `lsp-common-lib`: https://github.com/lsp-plugins/lsp-common-lib/commit/04c9a6e17cd4441be4196acec8ba6aeaf1644677

And to `lsp-3rd-party`: https://github.com/lsp-plugins/lsp-3rd-party/commit/045eb6baccc215343b70773a771b62f1e1f446df

**Comment by sadko4u** [comment]
Offtopic: is there a way of getting LoongArch64-base single-board computer and specification of the SIMD / vector instruction set extensions?

**Comment by zhangwenlong8911** [comment]
> Offtopic: is there a way of getting LoongArch64-base single-board computer and specification of the SIMD / vector instruction set extensions?
single-board computer can be bought online, and the documentation that has been open to the outside can be viewed here: https://github.com/loongson/loongarch-documentation

**Comment by sadko4u** [comment]
Available in 1.2.0.

**Pull request closed without merging**
