### PR TITLE
French translations improvements

### PR DESCRIPTION
**Pull request by trebmuh**
(_better than #100 since this one targets the devel branch_)

### CODE REVIEW

**Comment by sadko4u** [comment]
Thanks for basing branch on **devel**.

**Comment by sadko4u** [comment]
Merged changes into **devel**: b4ea7652a71316984082d5425f4cfc31958dc048
Preparing for 1.1.21 release

**Comment by sadko4u** [comment]
Changes available in 1.1.21 release!

**Comment by trebmuh** [comment]
thanks

**Pull request merged**
