### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by ignotus666**
Hi, I've created a Spanish translation; I'm not sure anything else needs to be added/changed apart from adding a line in each 'lang.json' file, to add "es": "Spanish" (which I don't know how to say in each language).

### CODE REVIEW

**Comment by sadko4u** [comment]
Hello!
Thank you for your contribution. I'll review your changes tomorrow.
If all is OK, I'll merge them into **devel** branch.

**Comment by sadko4u** [comment]
I've merged changes to **devel** branch: f9936ca60344ca7c6ec27c5bdcac327a009278ec
Seems to be working well:
image

**Comment by sadko4u** [comment]
Will close pull request after release

**Comment by ignotus666** [comment]
Ok good, I hope it's useful! I'll check in once in a while to see if it needs updating.

**Comment by sadko4u** [comment]
Available in 1.1.22 release!

**Pull request closed without merging**
