### PR TITLE
Update URLs to HTTPS

### PR DESCRIPTION
**Pull request by TotalCaesar659**
P.S. Please update URL here:

### CODE REVIEW

**Comment by sadko4u** [comment]
Hello!
What's the key benefit of migrating from HTTP protocol to HTTPS in URL string?
The site automatically redirects from HTTP to HTTPS when following the URL.

**Comment by TotalCaesar659** [comment]
It's just cosmetic improvement for perfectionists, plus the site gets rid of this redirect.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 8c2848ac78a105e8da74407d37a635b09679509d

**Comment by sadko4u** [comment]
Available in 1.1.29!

**Pull request merged**
