### PR TITLE
Adding XDG desktop files for all standalone JACK applications

### PR DESCRIPTION
**Pull request by dvzrv**
This adds [XDG desktop files](https://specifications.freedesktop.org/desktop-entry-spec/latest/) for all standalone JACK applications and [a specific menu](https://specifications.freedesktop.org/menu-spec/latest/) they will be shown in (because there are so many standalone applications).

The `*.desktop` files are to be installed to `/usr/share/applications/`, the `lsp-plugins.directory` to `/usr/share/desktop-directories` and the `lsp-plugin.menu` to `/etc/xdg/menus/applications-merged/` on a target system.

**To be done**: Adding (preferably) a vector graphic (`lsp-plugins.svg`) to be used as an icon, that can be installed to `/usr/share/icons/hicolor/scalable/apps/`.
(During packaging I used imagemagick's `convert` to resize [logo-large.png](https://github.com/sadko4u/lsp-plugins/blob/master/res/art/logo-large.png) to whatever sizes I need, but a single vector graphic would be nicer).

### CODE REVIEW

**Comment by dvzrv** [comment]
Hm... I just realized, I should replace all hyphen with underscores, or use subdirs [according to the spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html).

**Comment by dvzrv** [comment]
I think it should be correct now.

**Comment by sadko4u** [comment]
Hmm, I think We can get further and generate list of desktop entries at the build stage.
I'll merge your request after the 1.1.13 release that will be done this evening.

**Comment by dvzrv** [comment]
During build time I'm using [gendesk](https://github.com/xyproto/gendesk) (it's slightly Arch specific in regards to features though).
In general these files seldomly change though and it's fine to have them as plaintext IMHO.

Thanks for the consideration.

**Comment by trebmuh** [comment]
@sadko4u : if they would be auto-generated, how could we then add localised translations? _(I'm waiting for those to get merged, then will add French comments to those)._

**Comment by sadko4u** [comment]
Merged changes: 0ce6ffd7f8930d4ca2496ad2bc65866e1eb3ba49

**Comment by sadko4u** [comment]
@trebmuh 
I'm planning to implement multilingual interface which will allow to write JSON files which will contain translated strings.

**Comment by trebmuh** [comment]
Very nice !
Please ping me when done, I'll happily make a French translation then.

**Comment by sadko4u** [comment]
@trebmuh 
I've created special ticket: https://github.com/sadko4u/lsp-plugins/issues/65
If you have something to add to it, please leave messages there.

**Comment by sadko4u** [comment]
To complete this pull request, I've created Issue: https://github.com/sadko4u/lsp-plugins/issues/66
All further discussions we'll perform there.
Closing this pull request because it has been merged.

**Comment by sadko4u** [comment]
Changes available in 1.1.14 release!

**Pull request closed without merging**
