### PR TITLE
Fix categories and add keywords to the desktop files

### PR DESCRIPTION
**Pull request by DNS777**

### CODE REVIEW

**Comment by sadko4u** [comment]
Merged changes into **github-issue-83** branch: b86273e692d9e7bc946a77611dc73bae49cae937
Will be available in 1.1.15 release.

**Comment by sadko4u** [comment]
Changes have been applied partially. Modified 'Category' parameter has blown up multimedia menu with lots of LSP stuff instead of simple submenu 'LSP Plugins' as @dvzrv contributed previously.
So I reverted the change of 'Category' parameter for all *.desktop items.

**Comment by DNS777** [comment]
ok, sorry

**Comment by sadko4u** [comment]
Available in 1.1.15 release!

**Pull request closed without merging**
