### PR TITLE
Debian specs

### PR DESCRIPTION
**Pull request by mikhailnov**
Hello,
I am maintaining PulseEffects (https://github.com/wwmm/pulseeffects) Uhuntu PPA and `lsp-plugins` got needed for newest versions of PulseEffects.

So, I've packaged lsp-plugins into my PPAs. As there is no such package in Debian, I took `lsp-plugins` package sources from KXStudio and improved it:

* packaged ladspa, lv2, vst, jack plugins into seperate packages, while `lsp-plugins` package now is a meta-package that pulls all others as recommended dependencies
* allowed building for not i586 and x86_64 only, but also for armv7 and armv8

Builds and debug symbols are here:
https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects/+packages?field.name_filter=lsp-plugins&field.status_filter=published&field.series_filter=

So, I suggest to add `debian/` subdirectory to the main source to allow building a debian package directly from source, see https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source#debian--ubuntu

But, if you don't want to add distribution-specific files to the source tree, it's ok, because they require maintenance, it's not a problem to maintain them seperately.

### CODE REVIEW

**Comment by mikhailnov** [comment]
Oh, sorry, I forgot to package /usr/bin/*, will fix it now

**Comment by mikhailnov** [comment]
Fixed and squashed commits.

**Comment by trebmuh** [comment]
Nice improvements.

I'm the original maker of this debian package before it's been incorporated into KXstudio.
Can I ask why you removed my name and copyright holds in debian/copyright?

Another thing to correct in the very same file (d/copyright) is the license field for the upstream code which need to be moved from:
```
License: lsp-licence
 Please, see LICENSE.txt.
```
to

`License: GPL-3+`

Since they are now all released under this license.

Hope that helps.

**Comment by sadko4u** [comment]
@trebmuh one short notice:
> 
> `License: GPL-3+`
> 
> Since they are now all released under this license.

Plugins are licensed under terms of LGPL-3 license, not GPL-3.

@mikhailnov 
About this pull request: I'm not very happy to become supporter of debian package build system because I'm not a user of debian-based Linux distribution. I can merge changes but can not guarantee that once these specs become broken. If somebody will opportunely ship chanes as pull requests, then OK.
Second, is a '/debian' subdirectory strictly required? Can I create subdirectory like '/specs/debian' and merge changes there?

**Comment by trebmuh** [comment]
> Plugins are licensed under terms of LGPL-3 license, not GPL-3.

My bad. Thanks for correcting.

**Comment by falkTX** [comment]
I do not think debian folder should be in this repo.
Specially this one since it contains scripts specific to a person's private PPA.
Why should that be in a source code repo that has nothing to do with it?

UbuntuStudio team is working on getting lsp-plugins in ubuntu universe right now by the way.

And one final thing, for @mikhailnov 
What you did with the package is really not nice.
First, you split things from what was already there. So people that use librazik or kxstudio packages (where yours is based on) will get into conflicts when installing yours, and vice-versa.
Second, you removed copyright and attribution from the original packagers, that is really not playing nice.
Why would you just do that, basically just stealing someone's work without thinking?

**Comment by mikhailnov** [comment]
@falkTX 
> First, you split things from what was already there. So people that use librazik or kxstudio packages (where yours is based on) will get into conflicts when installing yours, and vice-versa.

No, they won't, because I made a meta-package `lsp-plugins` that pulls all other things that are not splitted in kxstudio as recommended dependencies. Also, kxstudio set epoch to 1 for some reason (you set it, why?), so there package will be have higher priority.

> UbuntuStudio team is working on getting lsp-plugins in ubuntu universe right now by the way.

I would appreciate if you split the package as I did. Debian and Ubuntu split packages as much as possible.

> Why should that be in a source code repo that has nothing to do with it?

It allows to git clone and build deb package directly from source. It is up to Vladimir to decide if it is needed or not, I just suggested.

> Specially this one since it contains scripts specific to a person's private PPA.

It allows to build the package in another PPA if I stop maintaining it. Again, I understand that it is not very relevant for source code repo.

@trebmuh  @falkTX 
> Second, you removed copyright and attribution from the original packagers, that is really not playing nice.
> Why would you just do that, basically just stealing someone's work without thinking?

I did not steal anything, everything is saved in debian/changelog. I hope to get pulseeffects and its dependencies to mainline debian one day, but see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881224 , how much time had passed before some one from debian answered, I don't have much motivation now.
I thought that debian specs under GPL violate debian policies, but https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ has an example of debian/* being under GPL, ok, I'll restore copyrights.

**Comment by falkTX** [comment]
Well, someone did the initial work of the packaging for you.
You took it, modify it and removed their name. So it will appear as you did the packaging yourself, which is not true.

I am not involved with UbuntuStudio or packaging for Ubuntu in general.
Looking at https://launchpad.net/~ubuntustudio-dev/+archive/ubuntu/autobuild/+packages I see it is based on the same package again haha.
So my guess is that it will be all together as well.

**Comment by mikhailnov** [comment]
> Looking at https://launchpad.net/~ubuntustudio-dev/+archive/ubuntu/autobuild/+packages I see it is based on the same package again haha.

They did not remove `/opt/kxstudio` and custom CFLAGS from `debian/rules`. That won't be accepted to Ubuntu, I hope.

I've fixed d/copyright with commit https://github.com/sadko4u/lsp-plugins/pull/43/commits/c60fe180826744e8a62eb8d0ffddd577aabc5873, thanks @trebmuh  and @falkTX 

@sadko4u 
> If somebody will opportunely ship chanes as pull requests, then OK.

Yes, I do like this in PulseEffects.

> Second, is a '/debian' subdirectory strictly required?

To allow to build deb directly from source - yes, /debian subdirectory is required, I don't know other ways.

**Comment by trebmuh** [comment]
Thanks for the copyright fixes.

**Comment by sadko4u** [comment]
I don't like an idea to add "/debian" folder to the root of the project. I even don't like the folder 'Polynomial-Wiener-Hammerstein' that @CrocoDuckoDucks has added to the root of the project and want to move it to '/submodules' folder in the nearest future.

Also @trebmuh @falkTX I don't understand the current state of copyright issues you've mentioned in the provided changes. Are they fixed now?

I can create a **lsp-plugins-specs** repository and add **lsp-plugins** as a submodule so you actually can deploy '/debian', '/ubuntu' or any other folders there related to different distro's build systems. But according to what @falkTX has said before, it seems to be not so necessary.

I appreciate your contribution but I need to think twice before merging it into the project's tree.

**Comment by eeickmeyer** [comment]
@mikhailnov I got your message. I've been packaging for Ubuntu, and as of this writing I have a working build regardless of the KXStudio-specific items in the d/rules file. So, that's not an issue.

Also, I don't intend on splitting-out the lv2/vst/ladspa versions as I believe it's not necessary. We've run into issues before when things have been split-out unnecessarily and I don't wish to repeat those issues in a new package.

That said, it's already on-track to be included in Ubuntu. However, it will not happen before 19.10 since beta freeze was yesterday for 19.04. So, I'd appreciate your patience on this matter. I will be revisiting it again in May.

I don't believe it is necessarily up to the upstream project developer (@sadko4u, in this case) to be worried about packaging since that's not really in their domain.

@mikhailnov, you might know that the reason I have started on lsp-plugins is because of your earlier request for packaging pulseeffects. I finally got to it, but realized that lsp-plugins needed to happen first. With that, I need you to be more patient as this process is extremely slow, especially if there are dependencies needed that aren't there. I hope to get it done before 19.10, but I can't make that promise. Thank you for your understanding.

**Comment by mikhailnov** [comment]
@sadko4u no problem ;-) that was just a suggestion.

@eeickmeyer I am quite pedentic in how distribution packages must be created, so I can't agree that CFLAGS and custom options that nobody except their original author understands are accepatable in d/rules. CFLAGS must be the same across the whole distribution, and @sadko4u probably does not test lsp-plugins with `-O3`, `-O2` is set by default. 

As for splitting, everything is very simple: dh_shlibs looks which libraries are needed by librarties in `lsp-plugins` and makes the whole package depend from libjack-jackd2-0, which conflicts with libjack0, so the user will not be able to install your package alongside jack1, only alongside jack2.

Spolitting solves all problems with tricky dependencies.

**Comment by eeickmeyer** [comment]
@mikhailnov First of all, I don't appreciate you emailing me personally telling me I "do it not very well." I had done it not 12 hours before you emailed me, and it was largely copied from what was already in the KXStudio repos. With that, I was merely getting started, and have it in a spot for testing purposes only. I'm only getting started on the entire process and I have a ton of resources to work with from all over Debian and Ubuntu. I intend to revisit lsp-plugins in May since that's when the repos for what will be Ubuntu 19.10 open.

**Pull request closed without merging**
