### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by sadko4u** [comment]
Olivier, thanks for tracking changes. Also please compare the latest changes between 'default' bundles and french ones. There were several additions for new plugins.

**Comment by trebmuh** [comment]
>... please compare the latest changes between 'default' bundles and french ones. There were several additions for new plugins.

I don't understand what you're referring to. I've looked at new commits in https://github.com/sadko4u/lsp-plugins/tree/master/res/i18n/fr . Should I watch some other places?

**Comment by sadko4u** [comment]
@trebmuh I mean you need compare json from:
https://github.com/sadko4u/lsp-plugins/tree/master/res/i18n/fr
with this folder:
https://github.com/sadko4u/lsp-plugins/tree/master/res/i18n/default

Since there are new records in the 'default' folder
You can do this in some diff viewer (like kdiff) since I try to keep the order of keys alphabetically sorted, so you'll easy find the missing ones in the 'fr' folder.

**Comment by trebmuh** [comment]
@sadko4u I've finally managed to find a bit of time to do so.
It looks to be fully updated now.
Please, noticed that I just made the translation and didn't checked if it compiles or not.
That said, it shouldn't break anything.

Note that I found a typo in the English source, I made another PR for that: #153 .

**Comment by trebmuh** [comment]
Hi @sadko4u
Just checking if you saw this PR.

**Comment by sadko4u** [comment]
Hello Olivier! Yes, I definitely saw this PR. I'm working on the upcoming release and will merge it before it gets to production.
I gave time to you so you could not open another PR if you wanted to add some additional changes.
If you think this PR is complete, I can merge it now.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 556bdd2c0d42d5490dd81d7ef3165608e76a0fc4

**Comment by trebmuh** [comment]
Thank you very much @sadko4u .

**Comment by sadko4u** [comment]
Available in 1.1.28 release!

**Pull request closed without merging**
