### PR TITLE
a small French translation fix

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
@sadko4u : please don't merge it yet, there might be other(s) I didn't spot yet. If so, I'll add those to this PR. And then, you can just merge this PR just before the next release.

**Comment by sadko4u** [comment]
OK, please let me know when you'll be ready.

**Comment by trebmuh** [comment]
whenever, I'm considering this PR as a "rolling PR", just merge it for the next release in order to ship the fixes I'll found by 1.1.18 .

**Comment by sadko4u** [comment]
Don't believe that it's possible to do rolling PR since github automatically closes pull requrests after they've been merged into **master**.

**Comment by trebmuh** [comment]
I mean "I'm considering this PR as a "_rolling PR till you merge it before the next version_". I'll open another one after if needed.

**Comment by sadko4u** [comment]
Please also look at the changes I've made in #95.

**Comment by sadko4u** [comment]
Sorry, I forgot to include this change in 1.1.19. Will be available in the next release.

**Comment by trebmuh** [comment]
No worries, that happens :wink:

**Comment by sadko4u** [comment]
Since I see #100 I'll merged these changes to **devel**.

**Comment by trebmuh** [comment]
Yes please, merge this one to devel.
I just realized I made a mistake on my side and erased the branch for this PR.

**Comment by sadko4u** [comment]
Changes available in 1.1.21 release!

**Comment by trebmuh** [comment]
thanks

**Pull request closed without merging**
